# Generated by Django 5.2.8 on 2025-11-06 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Service', 'Service'), ('Finance', 'Finance'), ('Membership', 'Membership'), ('Communication', 'Communication'), ('Leadership', 'Leadership'), ('CHIMPS', 'CHIMPS'), ('Meeting', 'Meeting')], max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pledge', 'Pledge')], max_length=20)),
                ('semester_joined', models.CharField(max_length=20)),
                ('dues_paid', models.BooleanField(default=False)),
                ('total_dues_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pledge', 'Pledge')], max_length=20)),
                ('category', models.CharField(choices=[('Service', 'Service'), ('Finance', 'Finance'), ('Membership', 'Membership'), ('Communication', 'Communication'), ('Leadership', 'Leadership'), ('CHIMPS', 'CHIMPS'), ('Meeting', 'Meeting')], max_length=30)),
                ('required_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semester', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HourLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.member')),
            ],
        ),
    ]
