# Generated by Django 5.2.8 on 2025-11-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlog',
            name='date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='hourlog',
            name='hours',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5),
        ),
    ]
