# Generated by Django 5.2.6 on 2025-11-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_hourlog_date_alter_hourlog_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterrequirement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='semesterrequirement',
            name='required_hours',
        ),
        migrations.RemoveField(
            model_name='semesterrequirement',
            name='status',
        ),
        migrations.AddField(
            model_name='semesterrequirement',
            name='chimps_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semesterrequirement',
            name='comm_hours_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semesterrequirement',
            name='finance_hours_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semesterrequirement',
            name='ld_hours_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semesterrequirement',
            name='membership_hours_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semesterrequirement',
            name='service_hours_required',
            field=models.IntegerField(default=0),
        ),
    ]
